# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocks.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstocks.proto\"\x14\n\x04\x44\x62ID\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\"M\n\x11NotingTransaction\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0b\n\x03qty\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\"*\n\nShareQuery\x12\x0c\n\x04\x64\x62id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\"\x1f\n\x10ShareQtyResponse\x12\x0b\n\x03qty\x18\x01 \x01(\x05\"\x1c\n\x0c\x46undResponse\x12\x0c\n\x04\x66und\x18\x01 \x01(\x02\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb3\x01\n\x16RegisteringTransaction\x12\x1f\n\x07GetFund\x12\x05.DbID\x1a\r.FundResponse\x12-\n\x0bGetShareQty\x12\x0b.ShareQuery\x1a\x11.ShareQtyResponse\x12#\n\x03\x42uy\x12\x12.NotingTransaction\x1a\x08.Message\x12$\n\x04Sell\x12\x12.NotingTransaction\x1a\x08.Messageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stocks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DBID']._serialized_start=16
  _globals['_DBID']._serialized_end=36
  _globals['_NOTINGTRANSACTION']._serialized_start=38
  _globals['_NOTINGTRANSACTION']._serialized_end=115
  _globals['_SHAREQUERY']._serialized_start=117
  _globals['_SHAREQUERY']._serialized_end=159
  _globals['_SHAREQTYRESPONSE']._serialized_start=161
  _globals['_SHAREQTYRESPONSE']._serialized_end=192
  _globals['_FUNDRESPONSE']._serialized_start=194
  _globals['_FUNDRESPONSE']._serialized_end=222
  _globals['_MESSAGE']._serialized_start=224
  _globals['_MESSAGE']._serialized_end=250
  _globals['_REGISTERINGTRANSACTION']._serialized_start=253
  _globals['_REGISTERINGTRANSACTION']._serialized_end=432
# @@protoc_insertion_point(module_scope)
